name = "phantomdrive"
type = "webpack"
workers_dev = true
account_id = "1fba8691d45f3422a3e3a44d1b1e4dab"
zone_id = "f5d18948a0200e0b1e362bd9414e8e48"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "cb1c2e99cf3244d698c3fd20c600e77b", id = "35ec88c313d54ac7af434cdcc295d66b" }
]

[env.staging]
name = "drive-staging"
